whitelist_rules:

# autocorrect rules

  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - implicit_return
  - joined_default_parameter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - literal_expression_end_indentation
  - mark
  - opening_brace
  - operator_usage_whitespace
  - private_over_fileprivate
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - return_arrow_whitespace
  - statement_position
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - vertical_whitespace
  - void_return

# opt-in rules

  - fatal_error_message
  - lower_acl_than_parent
  - modifier_order
  - multiline_parameters
  - object_literal
  - overridden_super_call
  - override_in_extension
  - private_action
#  - private_outlet
  - prohibited_super_call
  - unavailable_function
  - vertical_parameter_alignment_on_call
  - yoda_condition

# performance

  - contains_over_first_not_nil
#  - empty_count
  - empty_string
  - first_where
  - sorted_first_last

# other rules

  - block_based_kvo
  - class_delegate_protocol
  - closure_parameter_position
  - control_statement
  - discarded_notification_center_observer
  - discouraged_direct_init
  - dynamic_inline
  - for_where
  - implicit_getter
  - operator_whitespace
  - redundant_set_access_control
  - redundant_string_enum_value
  - shorthand_operator
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - unneeded_break_in_switch
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - weak_delegate

excluded:
  - Carthage
  - Pods
